[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kiwi"
version = "1.0.0"
description = "kiwi lib"
authors = [{ name = "kiwi", email = "kiwi@kiwi.kiwi" }]
readme = "README.md"
requires-python = ">=3.13.3"

dependencies = ["websocket-client"]

[tool.setuptools]
packages = ["kiwi"]
