from enum import Enum
import sys


class Key(Enum):
    Alt = "Alt"
    Backspace = "Backspace"
    CapsLock = "CapsLock"
    Control = "Control"
    Delete = "Delete"
    DownArrow = "DownArrow"
    End = "End"
    Escape = "Escape"
    F1 = "F1"
    F2 = "F2"
    F3 = "F3"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    F8 = "F8"
    F9 = "F9"
    F10 = "F10"
    F11 = "F11"
    F12 = "F12"
    F13 = "F13"
    F14 = "F14"
    F15 = "F15"
    F16 = "F16"
    F17 = "F17"
    F18 = "F18"
    F19 = "F19"
    F20 = "F20"
    Home = "Home"
    LeftArrow = "LeftArrow"
    Meta = "Meta"
    PageDown = "PageDown"
    PageUp = "PageUp"
    Return = "Return"
    RightArrow = "RightArrow"
    Shift = "Shift"
    Space = "Space"
    Tab = "Tab"
    UpArrow = "UpArrow"
    LeftBracket = "LeftBracket"
    RightBracket = "RightBracket"
    Num1 = "Num1"
    Num2 = "Num2"
    Num3 = "Num3"
    Num4 = "Num4"
    Num5 = "Num5"
    Num6 = "Num6"
    Num7 = "Num7"
    Num8 = "Num8"
    Num9 = "Num9"
    Num0 = "Num0"
    Minus = "Minus"
    Equal = "Equal"
    Q = "Q"
    W = "W"
    E = "E"
    R = "R"
    T = "T"
    Y = "Y"
    U = "U"
    I = "I"
    O = "O"
    P = "P"
    A = "A"
    S = "S"
    D = "D"
    F = "F"
    G = "G"
    H = "H"
    J = "J"
    K = "K"
    L = "L"
    Z = "Z"
    X = "X"
    C = "C"
    V = "V"
    B = "B"
    N = "N"
    M = "M"
    SemiColon = "SemiColon"
    Quote = "Quote"
    BackSlash = "BackSlash"
    Comma = "Comma"
    Dot = "Dot"
    Slash = "Slash"
    KpMinus = "KpMinus"
    KpPlus = "KpPlus"
    KpMultiply = "KpMultiply"
    KpDivide = "KpDivide"
    Kp0 = "Kp0"
    Kp1 = "Kp1"
    Kp2 = "Kp2"
    Kp3 = "Kp3"
    Kp4 = "Kp4"
    Kp5 = "Kp5"
    Kp6 = "Kp6"
    Kp7 = "Kp7"
    Kp8 = "Kp8"
    Kp9 = "Kp9"
    KpDelete = "KpDelete"
    BackQuote = "BackQuote"
    Insert = "Insert"
    PrintScreen = "PrintScreen"
    ScrollLock = "ScrollLock"
    Pause = "Pause"
    NumLock = "NumLock"

    # Function
    # IntlBackslash
    # Unknown(u32),
    # F21
    # F22
    # F23
    # F24
